<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\CommandCentral.Core\CommandCentral.Core.csproj" />
    <ProjectReference Include="..\CommandCentral.Input\CommandCentral.Input.csproj" />
    <ProjectReference Include="..\CommandCentral.Output\CommandCentral.Output.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5915e0ec-2e2a-44a0-8196-bed0d24cb7c5</UserSecretsId>
  </PropertyGroup>

</Project>
